server:
  port: 8070

spring:
  application:
    name: SPServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/streaming
    username: root
    password: adminuser
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587 # smtp 주로 사용되는 port
    username: # 보내는 사람 이메일
    password: # 암호화된 비밀번호 발급 필요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

kakao:
  client_id: # rest API
  redirect_uri: http://localhost:8070/member/kakaoLogin

